# Generated by Django 4.2.7 on 2023-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.windhorsepublications.com/wp-content/uploads/2019/11/image-coming-soon-placeholder.png', max_length=500),
        ),
    ]
