# Generated by Django 4.2.7 on 2023-12-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
