# Generated by Django 4.2.7 on 2023-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('m', 'Mens'), ('f', 'Womens'), ('k', 'Kids')], default="('m','Mens')", max_length=1),
        ),
    ]
