# Generated by Django 5.0.1 on 2024-01-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_desc', models.TextField()),
                ('item_image', models.ImageField(upload_to='watch_images/')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
