# Generated by Django 5.0.1 on 2024-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='quantity_in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
